# Generated by Django 2.2.3 on 2019-11-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20191128_1337'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=5)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('middle_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('street_1', models.CharField(blank=True, default='', max_length=128)),
                ('street_2', models.CharField(blank=True, default='', max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('region', models.CharField(default='', max_length=128)),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('work_phone', models.CharField(blank=True, default='', max_length=16)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=16)),
                ('email', models.CharField(blank=True, default='', max_length=256)),
                ('role', models.CharField(blank=True, default='', max_length=256)),
                ('notes', models.TextField(blank=True, max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='DomainProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(blank=True, default='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_temp', models.TextField(blank=True, default='')),
                ('domains', models.TextField(blank=True, default='')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.Domain')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='domainprofile',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.DomainProfile'),
        ),
    ]
