# Generated by Django 2.2.3 on 2019-11-08 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from assessments.seed.init import init


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('score', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=64)),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple', models.BooleanField(default=False)),
                ('max_score', models.PositiveIntegerField()),
                ('content', models.CharField(default='', max_length=1024)),
                ('recommendation', models.CharField(blank=True, default='', max_length=1024)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Question'),
        ),
        migrations.RunPython(init)
    ]
